[package]
name = "jedec-spi-nor"
version = "0.1.0"
edition = "2021"

authors = ["Logiase <logiase.syx@gmail.com"]
repository = "https://github.com/Logiase/jedec-spi-nor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
